sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo # build hexo branch only
before_install:
  - git clone https://github.com/theme-next/theme-next-reading-progress themes/next/source/lib/reading_progress
  - git clone https://github.com/theme-next/theme-next-pangu.git themes/next/source/lib/pangu
  - git clone https://github.com/theme-next/theme-next-bookmark.git themes/next/source/lib/bookmark
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    # solve "Skipping a deployment with the pages provider because this branch 
    # is not permitted"
    all_branches: true
  target_branch: master
  local-dir: public