# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html

title: Shank's Notes
subtitle: Code & Tech & Life
description: Nothing or Anything
author: sko00o
language: en
timezone: Asia/Shanghai
url: https://www.findshank.com
root: /
external_link: true
post_asset_folder: true
index_generator:
  per_page: 7
per_page: 7
theme: next
deploy:
  type: git
  repo: https://github.com/sko00o/sko00o.github.io # git@github.com:sko00o/sko00o.github.io.git
  branch: master
